version: '3.8'
services:
    api:
        image: api
        build: 
          context: .
          dockerfile: Dockerfile
        deploy:
          replicas: 1
          restart_policy:
             condition: any
          update_config:
             parallelism: 2
             delay: 15s
        ports:
            - "3080:3080"
        links:
            - mongo
    mongo:
        image: mongo:4.2
        deploy:
          replicas: 1
          restart_policy:
             condition: any
          update_config:
             parallelism: 2
             delay: 15s
        ports:
            - "27017:27017"
        expose:
            - "27017-27019"
        volumes:
            - ./data:/data/db
